In [32]:
import numpy as np

b) Создайте массив из 10 нулей

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

c) Создать массив из 10 единиц

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

d) Создать массив из 10 пятерок

In [35]:
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

e) Создать массив из целых чисел от 10 до 50

In [36]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

f) Создать массив из четных чисел от 10 до 50

In [37]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

g) Создать матрицу 3х3 с числами от 0 до 8

In [38]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

h) Создать единичную матрицу 3x3

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

i) Используйте NumPy для генерации случайного числа от 0 до 1

In [40]:
np.random.random()

0.8014756823991761

j) Используйте NumPy для генерации массива из 25 случайных чисел,
взятых из стандартного нормального распределения

In [41]:
np.random.randn(25)

array([ 0.63281287, -1.0736941 ,  0.82995322,  0.01445229, -0.58026273,
        0.34754163, -0.29270259,  2.27438285, -0.16093012,  1.07832584,
        0.66372332,  1.07844341, -0.2058355 , -0.3258482 ,  0.15295365,
        0.46396748, -0.54043272, -0.41952501,  3.26317854,  0.01607445,
       -0.41606494,  0.87191919, -0.80556571,  0.34509924,  0.7324448 ])

k)

In [42]:
np.arange(0.01, 1.01, 0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

L)

In [43]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)

In [44]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [45]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

M) Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи L.

In [46]:
mat[3, -1]

20

n)

In [47]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

o)

In [48]:
mat[4:]

array([[21, 22, 23, 24, 25]])

p)

In [49]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

q) Получить сумму всех значений в стартовой матрице mat

In [50]:
mat.sum()

325

r) Получить стандартное отклонение в стартовой матрице mat

In [51]:
mat.std()

7.211102550927978

s) Получить сумму значений в колонках в стартовой матрице mat

In [52]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
mat[:, 0].sum()

55

In [54]:
mat[:, 1].sum()

60

In [55]:
mat[:, 2].sum()

65

In [56]:
mat[:, 3].sum()

70

In [57]:
mat[:, 4].sum()

75